[package]
name = "evm-from-scrust"
version = "0.1.0"
edition = "2021"
authors = ["0xrusowsky"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]